### ISSUE TITLE
Riferimenti protocolli

### ISSUE THREAD

**Issue by biagiosaitta** [AbulafiaSysNSol/abulafia#21]
Aggiungere la possibilità di referenziare un protocollo ad un altro già registrato nel sistema

**Comment by biagiosaitta** [comment]
@alfiomusmarra pensi possa essere una cosa utile?

**Comment by alfiomusmarra** [comment]
Teoricamente sarebbe la stessa cosa di "fascicolo" o "tag" o "pratica", che
anzi consentono di mettere in relazione più documenti e non solo una coppia
alla volta

Il mar 9 apr 2019, 20:42 Biagio <notifications@github.com> ha scritto:

**Comment by biagiosaitta** [comment]
ok chiudo allora.
