### ISSUE TITLE
[PDO] Documenti/aggiungi categorie

### ISSUE THREAD

**Issue by alfiomusmarra** [AbulafiaSysNSol/abulafia#73]
Documenti/aggiungi categorie non funziona. 
1) Se il numero di lettere è inferiore al minimo, non aggiunge la categoria e non segnala il motivo
2) Se il numero di lettere è sufficiente, la query fallisce per "tabella non presente"

**Comment by biagiosaitta** [comment]
mancava tabella nl DB
