### ISSUE TITLE
[PDO] upload foto fallisce

### ISSUE THREAD

**Issue by alfiomusmarra** [AbulafiaSysNSol/abulafia#75]
Upload foto restituisce undevined variable urlfoto e fallisce

**Comment by biagiosaitta** [comment]
@alfiomusmarra in che pagina e in quale version? Non riesco a replicare l'errore

**Comment by alfiomusmarra** [comment]
Branch PDO. Se il file è superiore alla dimensione massima non bisogna
tentare di valorizzare le variabili per non avere un notice.

Alfio

**Comment by biagiosaitta** [comment]
A me funziona, se la dimensione supera il limite mi ritorna l'errore come nello screen
![Immagine](https://user-images.githubusercontent.com/3852048/55613480-1374c080-578b-11e9-8e5d-f7604fb145b9.jpg)

**Comment by alfiomusmarra** [comment]
Beh, chiudi, poi controllo meglio. Intanto ho scoperto che upload foto ti
lascia caricare anche un pdf, non funziona più il filtro per estensione del
file (jpg, png, etc)

Alfio

**Comment by biagiosaitta** [comment]
Hai ragione, lascio aperto e correggo questa cosa
