### ISSUE TITLE
Inserimento prodotti nel documento

### ISSUE THREAD

**Issue by ico88** [AbulafiaSysNSol/abulafia#87]
Permettere l'inserimento nel documento di carico/scarico di un prodotto per codice. Nello specifico:
- digitare codice e premere invio
- inserire quantità premere invio
- fine inserimento
- cursore ritorna su codice se inserito per codice, su nome se inserito per nome

**Comment by biagiosaitta** [comment]
@ico88 posso chiudere?

**Comment by ico88** [comment]
Si si perfetto, confermo il funzionamento
